### ISSUE TITLE
How can I run the code?

### ISSUE THREAD

**Issue by brunaostii** [asiviero/fuzzy_time_series_predictor#1]
I downloaded the code but I can't figure out how I can execute, can you help me ?

**Comment by asiviero** [comment]
hi @brunaostii , cleaning up my github, saw this issue. My interests have since shifted and at the time of writing this code, I didn't worry about dependency handling or anything that would make running the code easy. As I'm no longer working on this repository, I can review contributions if someone is looking to run this again, but I won't do them myself in any near future, apologies for that
